name: mapguaru
description: Seu guia digital completo e acessível para os serviços públicos de Guarulhos."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Banco de dados SQL (SQLite)
  sqflite: any
  path: any

  # Firebase (Core e Autenticação)
  firebase_core: any
  firebase_auth: any
  
  # Mapa (OpenStreetMap via flutter_map)
  flutter_map: any # Pacote de mapas open-source
  latlong2: any # Dependência para coordenadas do flutter_map

  # Gerenciamento de estado
  provider: any
  
  # Criptografia para senhas
  crypto: any
  
  # Ícones
  cupertino_icons: any
  
  # HTTP requests (se necessário)
  http: any
  
  # XML
  xml: any
  
  # Shared Preferences para dados simples
  shared_preferences: any

  # Brand icons
  font_awesome_flutter: any

  # Ligações telefônicas
  url_launcher: ^6.2.2
  
  # Formatação de datas
  intl: ^0.18.1

  # Rota para localização do usuário
  geolocator: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/world_map.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/metadata/

  # Para adicionar a fonte Helvetica
  # 1. Crie uma pasta 'assets' na raiz do seu projeto.
  # 2. Dentro de 'assets', crie uma pasta 'fonts'.
  # 3. Coloque o arquivo Helvetica.ttf dentro de 'assets/fonts/'.
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700